#!/usr/bin/python

import sys
import subprocess

pipe = subprocess.Popen('git describe', stdout=subprocess.PIPE, shell=True)
current_revision = pipe.stdout.read()

print "revision: %s" % current_revision

from xml.dom.minidom import parse, parseString
dom = parse("AndroidManifest.xml")
manifest = dom.documentElement
if manifest.hasAttribute('android:versionName'):
	versionName = manifest.getAttribute('android:versionName')
	manifest.setAttribute('android:versionName', "%s" % (current_revision))
	xml = open("AndroidManifest.xml", "w")
	dom.writexml(xml)
	xml.close()
	subprocess.call('git add AndroidManifest.xml', shell=True)
else:
	sys.stderr.write("versionName not defined!\n")
	sys.exit(2)
